### ISSUE TITLE
Error messages should be more specific and secure (when no login or/and password is specified)

### ISSUE THREAD

**Issue by Andrew-Kiev** [Andrew-Kiev/web.test#2]
1) Specify Login but do not specify password
2) Click Login button
**Actual result:** "Incorrect password!" notification message is shown
**Expected result:** Should be more relevant and secure, e.g. "Please specify password!". This message should not depend on weather specified login is correct or not.

3) Specify password but do not specify Login  
4) Click Login button
**Actual result:** "Incorrect user name!" notification message is shown
**Expected result:** Should be more relevant and secure, e.g. "Please specify user name (login)!". This message should not depend on weather specified password is correct or not.

5) Leave empty both Login and Password fields  
6) Click Login button
**Actual result:** "User not found!" notification message is shown
**Expected result:** Should be more relevant, e.g. "Please specify user name (login) and password!".

**Comment by varajan** [comment]
Login/Password cannot be empty!
