### ISSUE TITLE
Error messages should be more specific and secure (when incorrect login or password or both are specified)

### ISSUE THREAD

**Issue by Andrew-Kiev** [Andrew-Kiev/web.test#3]
Error messages should be more specific and secure (when incorrect login or password or both are specified)

1) Set incorrect login but correct password 
2) Click Login button
**Actual result:** "Incorrect user name!" notification message is shown
**Expected result:** Should be more secure, e.g. "Incorrect User name (Login)/Password!".

3) Set incorrect password but correct login  
4) Click Login button
**Actual result:** "Incorrect password!" notification message is shown
**Expected result:** Should be more secure, e.g. "Incorrect User name (Login)/Password!".

5) Set incorrect login and password 
6) Click Login button
**Actual result:** "User not found!" notification message is shown
**Expected result:** Should be more secure, e.g. "Incorrect User name (Login)/Password!".

**Comment by varajan** [comment]
Incorrect Login/Password!
